// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../../../index.js";

export interface ListPublicIpsResponse extends AmericancloudApi.PaginatedResponseDto {
    data: AmericancloudApi.PublicIpResponseDto[];
}
