// This file was auto-generated by Fern from our API Definition.

import { BlockStorageClient } from "./api/resources/blockStorage/client/Client.js";
import { DatabaseBackupsClient } from "./api/resources/databaseBackups/client/Client.js";
import { DatabaseInfrastructureClient } from "./api/resources/databaseInfrastructure/client/Client.js";
import { DatabaseOfferingsClient } from "./api/resources/databaseOfferings/client/Client.js";
import { DatabaseOperationsClient } from "./api/resources/databaseOperations/client/Client.js";
import { DatabaseRegionsClient } from "./api/resources/databaseRegions/client/Client.js";
import { DatabasesClient } from "./api/resources/databases/client/Client.js";
import { DnsRecordsClient } from "./api/resources/dnsRecords/client/Client.js";
import { DnsZonesClient } from "./api/resources/dnsZones/client/Client.js";
import { EgressRulesClient } from "./api/resources/egressRules/client/Client.js";
import { FirewallRulesClient } from "./api/resources/firewallRules/client/Client.js";
import { ImagesClient } from "./api/resources/images/client/Client.js";
import { IsolatedNetworksClient } from "./api/resources/isolatedNetworks/client/Client.js";
import { KubernetesClient } from "./api/resources/kubernetes/client/Client.js";
import { LoadBalancerRulesClient } from "./api/resources/loadBalancerRules/client/Client.js";
import { NetworkAclsClient } from "./api/resources/networkAcls/client/Client.js";
import { ObjectStorageClient } from "./api/resources/objectStorage/client/Client.js";
import { PortForwardingClient } from "./api/resources/portForwarding/client/Client.js";
import { PublicIpsClient } from "./api/resources/publicIps/client/Client.js";
import { RegionsClient } from "./api/resources/regions/client/Client.js";
import { SnapshotsClient } from "./api/resources/snapshots/client/Client.js";
import { SshKeysClient } from "./api/resources/sshKeys/client/Client.js";
import { VmPackagesClient } from "./api/resources/vmPackages/client/Client.js";
import { VmsClient } from "./api/resources/vms/client/Client.js";
import { VpcNetworksClient } from "./api/resources/vpcNetworks/client/Client.js";
import { WordpressClient } from "./api/resources/wordpress/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace AmericancloudApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AmericancloudApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AmericancloudApiClient.Options>;
    protected _vms: VmsClient | undefined;
    protected _vmPackages: VmPackagesClient | undefined;
    protected _regions: RegionsClient | undefined;
    protected _images: ImagesClient | undefined;
    protected _isolatedNetworks: IsolatedNetworksClient | undefined;
    protected _vpcNetworks: VpcNetworksClient | undefined;
    protected _publicIps: PublicIpsClient | undefined;
    protected _firewallRules: FirewallRulesClient | undefined;
    protected _portForwarding: PortForwardingClient | undefined;
    protected _loadBalancerRules: LoadBalancerRulesClient | undefined;
    protected _egressRules: EgressRulesClient | undefined;
    protected _networkAcls: NetworkAclsClient | undefined;
    protected _databases: DatabasesClient | undefined;
    protected _databaseBackups: DatabaseBackupsClient | undefined;
    protected _databaseOfferings: DatabaseOfferingsClient | undefined;
    protected _databaseRegions: DatabaseRegionsClient | undefined;
    protected _databaseInfrastructure: DatabaseInfrastructureClient | undefined;
    protected _databaseOperations: DatabaseOperationsClient | undefined;
    protected _dnsZones: DnsZonesClient | undefined;
    protected _dnsRecords: DnsRecordsClient | undefined;
    protected _kubernetes: KubernetesClient | undefined;
    protected _objectStorage: ObjectStorageClient | undefined;
    protected _sshKeys: SshKeysClient | undefined;
    protected _blockStorage: BlockStorageClient | undefined;
    protected _snapshots: SnapshotsClient | undefined;
    protected _wordpress: WordpressClient | undefined;

    constructor(options: AmericancloudApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get vms(): VmsClient {
        return (this._vms ??= new VmsClient(this._options));
    }

    public get vmPackages(): VmPackagesClient {
        return (this._vmPackages ??= new VmPackagesClient(this._options));
    }

    public get regions(): RegionsClient {
        return (this._regions ??= new RegionsClient(this._options));
    }

    public get images(): ImagesClient {
        return (this._images ??= new ImagesClient(this._options));
    }

    public get isolatedNetworks(): IsolatedNetworksClient {
        return (this._isolatedNetworks ??= new IsolatedNetworksClient(this._options));
    }

    public get vpcNetworks(): VpcNetworksClient {
        return (this._vpcNetworks ??= new VpcNetworksClient(this._options));
    }

    public get publicIps(): PublicIpsClient {
        return (this._publicIps ??= new PublicIpsClient(this._options));
    }

    public get firewallRules(): FirewallRulesClient {
        return (this._firewallRules ??= new FirewallRulesClient(this._options));
    }

    public get portForwarding(): PortForwardingClient {
        return (this._portForwarding ??= new PortForwardingClient(this._options));
    }

    public get loadBalancerRules(): LoadBalancerRulesClient {
        return (this._loadBalancerRules ??= new LoadBalancerRulesClient(this._options));
    }

    public get egressRules(): EgressRulesClient {
        return (this._egressRules ??= new EgressRulesClient(this._options));
    }

    public get networkAcls(): NetworkAclsClient {
        return (this._networkAcls ??= new NetworkAclsClient(this._options));
    }

    public get databases(): DatabasesClient {
        return (this._databases ??= new DatabasesClient(this._options));
    }

    public get databaseBackups(): DatabaseBackupsClient {
        return (this._databaseBackups ??= new DatabaseBackupsClient(this._options));
    }

    public get databaseOfferings(): DatabaseOfferingsClient {
        return (this._databaseOfferings ??= new DatabaseOfferingsClient(this._options));
    }

    public get databaseRegions(): DatabaseRegionsClient {
        return (this._databaseRegions ??= new DatabaseRegionsClient(this._options));
    }

    public get databaseInfrastructure(): DatabaseInfrastructureClient {
        return (this._databaseInfrastructure ??= new DatabaseInfrastructureClient(this._options));
    }

    public get databaseOperations(): DatabaseOperationsClient {
        return (this._databaseOperations ??= new DatabaseOperationsClient(this._options));
    }

    public get dnsZones(): DnsZonesClient {
        return (this._dnsZones ??= new DnsZonesClient(this._options));
    }

    public get dnsRecords(): DnsRecordsClient {
        return (this._dnsRecords ??= new DnsRecordsClient(this._options));
    }

    public get kubernetes(): KubernetesClient {
        return (this._kubernetes ??= new KubernetesClient(this._options));
    }

    public get objectStorage(): ObjectStorageClient {
        return (this._objectStorage ??= new ObjectStorageClient(this._options));
    }

    public get sshKeys(): SshKeysClient {
        return (this._sshKeys ??= new SshKeysClient(this._options));
    }

    public get blockStorage(): BlockStorageClient {
        return (this._blockStorage ??= new BlockStorageClient(this._options));
    }

    public get snapshots(): SnapshotsClient {
        return (this._snapshots ??= new SnapshotsClient(this._options));
    }

    public get wordpress(): WordpressClient {
        return (this._wordpress ??= new WordpressClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
