// This file was auto-generated by Fern from our API Definition.

export interface AssignVmsToLoadBalancerRuleDto {
    /** Identifiers of the VMs to attach as backends for the rule. */
    vmIds: string[];
}
