// This file was auto-generated by Fern from our API Definition.

export interface BackupScheduleItemDto {
    /** Name of this schedule entry. */
    name: string;
    /** Backup method to use for runs of this schedule. */
    backupMethod: BackupScheduleItemDto.BackupMethod;
    /** Cron expression describing when the schedule fires. */
    cronExpression: string;
    /** How long to keep each backup produced by this schedule. */
    retentionPeriod?: string | undefined;
    /** Whether this schedule is active. */
    enabled?: boolean | undefined;
}

export namespace BackupScheduleItemDto {
    /** Backup method to use for runs of this schedule. */
    export const BackupMethod = {
        Xtrabackup: "xtrabackup",
        PgBasebackup: "pg-basebackup",
        Datafile: "datafile",
    } as const;
    export type BackupMethod = (typeof BackupMethod)[keyof typeof BackupMethod];
}
