// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../index.js";

export interface CostBreakdownDto {
    /** Base cost before any discounts */
    base: number;
    /** Discount amount applied */
    discount: number;
    /** Final cost after discounts */
    total: number;
    /** Prorated cost details (only present for monthly estimates) */
    prorated?: AmericancloudApi.ProratedEstimateDto | undefined;
}
