// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../index.js";

export interface CreateVmResponseDto {
    /** Unique identifier for this virtual machine. */
    id: string;
    /** Human-readable name for the VM. Shown in dashboards and CLI output. */
    name: string;
    /** Current lifecycle state of the VM. */
    status: string;
    /** Region the VM is provisioned in. References a region label from /v1/compute/regions. */
    region: string;
    /** Package label identifying the CPU/memory/disk preset this VM uses. */
    vmPackage?: string | undefined;
    /** Number of virtual CPUs allocated to the VM. */
    cpu: number;
    /** Memory allocated to the VM, in megabytes. */
    memoryMb: number;
    /** Root disk size, in gigabytes. */
    rootDiskGb: number;
    /** Tags assigned to this VM for grouping and filtering. */
    tags?: string[] | undefined;
    /** Billing cadence applied to this VM. */
    subscriptionPeriod: string;
    /** Image label the VM was provisioned from. References /v1/compute/images. */
    image: string;
    /** Friendly name of the source image. */
    imageDisplayName?: string | undefined;
    /** Primary IP address assigned to the VM on its network. */
    ipAddress: string;
    /** Name of the network or VPC tier this VM is attached to. */
    networkName: string;
    /** Identifier of the network or VPC tier this VM is attached to. */
    networkId: string;
    /** Identifier of the VM root volume. */
    rootVolumeId: string;
    /** When the VM was first provisioned. */
    createdAt: string;
    /** When the current billing version started (set when the VM is scaled or its disk is resized). Only present if the VM has been modified since creation. */
    versionStartedAt?: string | undefined;
    /** Source marketplace app, when the VM was deployed from one. Absent for OS-only deploys. */
    marketplaceApp?: AmericancloudApi.MarketplaceAppDto | undefined;
    /** Human-readable note explaining how the initial VM password will be delivered. */
    passwordMessage: string;
}
