// This file was auto-generated by Fern from our API Definition.

export interface CreateWordPressDto {
    /** Package label to use for the WordPress instance */
    packageLabel: string;
    /** Optional custom domain for the WordPress site */
    domain?: (string | null) | undefined;
}
