// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../index.js";

export interface CreateVmDto {
    /** VM name. It must be 1 to 63 characters, start with a letter, end with a letter or a digit, and hold only letters, digits and hyphens. */
    name: string;
    /** Region label */
    region: string;
    /** VM package label */
    vmPackage: string;
    /** VM specifications */
    vmSpecs: AmericancloudApi.VmSpecsDto;
    /** Image label to use for the VM */
    image: string;
    /** UUID of a pre-existing network to attach the VM to. Omit to have an isolated network auto-created for the VM (post-create access is then configured via `networkAccess`). An auto-created network is deleted with the VM once its last VM is removed; a network you supply is not. */
    network?: string | undefined;
    /** Subscription period */
    subscriptionPeriod: CreateVmDto.SubscriptionPeriod;
    /** List of tags to add to the VM */
    tags?: string[] | undefined;
    /** Names of SSH key pairs to use (optional) */
    keypairs?: string[] | undefined;
    /** Base64-encoded cloud-init userdata script (optional) */
    userdata?: string | undefined;
    /** Optional network access configuration applied after the VM is created. Only honored when no `network` is provided (i.e. an isolated network is auto-created). Applies the requested outbound traffic setting and adds port forwarding + firewall rules for the requested inbound ports against the network's public IP. */
    networkAccess?: AmericancloudApi.NetworkAccessDto | undefined;
}

export namespace CreateVmDto {
    /** Subscription period */
    export const SubscriptionPeriod = {
        Hourly: "hourly",
        Monthly: "monthly",
    } as const;
    export type SubscriptionPeriod = (typeof SubscriptionPeriod)[keyof typeof SubscriptionPeriod];
}
