// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../index.js";

export interface DetailedVpcNetworkResponseDto {
    /** Unique identifier for the VPC */
    id: string;
    /** Name of the VPC */
    name: string;
    /** Description of the VPC */
    description: string;
    /** CIDR of the VPC */
    cidr: string;
    /** VPC status */
    status: DetailedVpcNetworkResponseDto.Status;
    /** Region where the VPC is located */
    region: string;
    /** VPC creation date */
    createdAt?: string | undefined;
    /** Network tiers in this VPC */
    tiers: AmericancloudApi.VpcTierResponseDto[];
    /** Public IP addresses associated with this VPC */
    publicIps: string[];
}

export namespace DetailedVpcNetworkResponseDto {
    /** VPC status */
    export const Status = {
        Active: "Active",
        Inactive: "Inactive",
        Creating: "Creating",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
