// This file was auto-generated by Fern from our API Definition.

export interface DiscountAppliedDto {
    /** Name of the discount/coupon */
    name: string;
    /** Discount percentage */
    percent: number;
    /** Resource types the discount applies to */
    resource_types: string[];
}
