// This file was auto-generated by Fern from our API Definition.

export interface IsolatedNetworkConfigDto {
    /** Identifier of the isolated network the cluster will attach to. */
    networkId: string;
    /** Zone name override for the cluster. */
    zoneName?: string | undefined;
}
