// This file was auto-generated by Fern from our API Definition.

export interface KubernetesNodePool {
    /** Number of control-plane nodes in the cluster. */
    controlNodes: number;
    /** Number of worker nodes in the cluster. */
    workerNodes: number;
    /** Whether the cluster scales worker nodes automatically based on load. */
    autoscalingEnabled: boolean;
    /** Floor for worker-node count when autoscaling is enabled. */
    minWorkers?: number | undefined;
    /** Ceiling for worker-node count when autoscaling is enabled. */
    maxWorkers?: number | undefined;
    /** Number of virtual CPU cores allocated to each node. */
    cpuCores: number;
    /** Memory allocated to each node, in megabytes. */
    memoryMb: number;
}
