// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../index.js";

export interface KubernetesClusterResponse {
    /** Unique identifier for the cluster. */
    id: string;
    /** Human-readable name for the cluster. */
    name: string;
    /** Region the cluster is deployed in. */
    region: string;
    /** Current lifecycle state of the cluster. */
    status: string;
    /** Kubernetes version the cluster is running. */
    kubernetesVersion: string;
    /** When the cluster was created. */
    createdAt: string;
    /** Package label describing the per-node CPU/memory/disk preset. */
    package: string;
    /** Description of the cluster. */
    description: string;
    /** Public IP address attached to the cluster. */
    ipAddress?: string | undefined;
    /** Identifier of the public IP attached to the cluster. */
    ipAddressId?: string | undefined;
    /** Node-pool configuration for the cluster. */
    nodePool: AmericancloudApi.KubernetesNodePool;
    /** When the cluster was deleted. Omitted if the cluster still exists. */
    deletedAt?: string | undefined;
    /** Cluster nodes. Only included when `details=true`. */
    nodes?: AmericancloudApi.KubernetesNodeResponse[] | undefined;
}
