// This file was auto-generated by Fern from our API Definition.

export interface MaxInstancesDto {
    /** Whether the operation succeeded. */
    success: boolean;
    /** Maximum number of WordPress instances the account may create. */
    maxInstances?: number | undefined;
    /** Error message describing why the operation failed. */
    message?: string | undefined;
}
