// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../index.js";

export interface ModifyBackupScheduleRequestDto {
    /** Name of the schedule group being modified. */
    scheduleName: string;
    /** Backup policy these schedules will be applied to. */
    backupPolicyName: string;
    /** Schedule entries that make up the policy. */
    schedules: AmericancloudApi.BackupScheduleItemDto[];
    /** Whether point-in-time recovery is enabled for the cluster. */
    pitrEnabled: boolean;
}
