// This file was auto-generated by Fern from our API Definition.

export interface NetworkAclListResponseDto {
    /** Unique identifier for the ACL list. */
    id: string;
    /** Human-readable name for the ACL list. */
    name: string;
    /** Free-form description of the ACL list. */
    description?: string | undefined;
    /** Identifier of the parent VPC the ACL list belongs to. Absent for the account-wide default lists (`default_allow`, `default_deny`). */
    vpcId?: string | undefined;
    /** When the ACL list was created. */
    createdAt?: string | undefined;
}
