// This file was auto-generated by Fern from our API Definition.

export interface PortForwardingRuleResponseDto {
    /** Unique identifier for the port forwarding rule. */
    id: string;
    /** Port on the VM that traffic is forwarded to. */
    privatePort: number;
    /** Port on the public IP that receives the inbound traffic. */
    publicPort: number;
    /** Protocol the forwarding rule applies to. `TCP` or `UDP`. */
    protocol: string;
    /** Identifier of the VM the forwarded traffic is delivered to. */
    vmId: string;
    /** Name of the VM the forwarded traffic is delivered to. */
    vmName: string;
    /** Identifier of the public IP the rule is attached to. */
    ipAddressId: string;
    /** Public IP address the rule is attached to. */
    ipAddress: string;
    /** Current lifecycle state of the rule. */
    state: string;
    /** When the rule was created. */
    createdAt?: string | undefined;
}
