// This file was auto-generated by Fern from our API Definition.

export interface SnapshotResponseDto {
    /** Unique identifier of the snapshot */
    id: string;
    /** Name of the snapshot */
    name: string;
    /** Size of the snapshot in GB */
    sizeGb: number;
    /** Current status of the snapshot */
    status: string;
    /** Type of the snapshot, indicating whether it was taken of a root or data disk. */
    type: SnapshotResponseDto.Type;
    /** ID of the volume the snapshot was created from, if any */
    volumeId: string;
    /** Label of the region where the snapshot is located */
    region: string;
    /** When the snapshot was created */
    createdAt: string;
    /** ID of the virtual machine the snapshot was created from, if any */
    vmId: string | null;
}

export namespace SnapshotResponseDto {
    /** Type of the snapshot, indicating whether it was taken of a root or data disk. */
    export const Type = {
        DataDisk: "DataDisk",
        RootDisk: "RootDisk",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
