// This file was auto-generated by Fern from our API Definition.

export interface ValidationErrorItemDto {
    /** Dotted path to the field that failed validation. */
    field: string;
    /** Human-readable validation message for this field. */
    message: string;
}
