// This file was auto-generated by Fern from our API Definition.

export interface VmConsoleResponseDto {
    /** Signed console URL for accessing the VM. Single-use; request a new one if it expires. */
    url: string;
}
