// This file was auto-generated by Fern from our API Definition.

export interface VmMetricSampleDto {
    /** Sample timestamp from the underlying compute platform. */
    timestamp: string;
    /** CPU usage as a percentage (0–100), rounded to two decimal places. */
    cpuUsagePct: number;
    /** Memory usage as a percentage (0–100), rounded to two decimal places. */
    memoryUsagePct: number;
}
