// This file was auto-generated by Fern from our API Definition.

export interface VmSpecsDto {
    /** Number of virtual CPUs */
    vcpu: number;
    /** Memory in MB */
    memoryMb: number;
    /** Root disk size in GB */
    rootDiskGb: number;
}
