// This file was auto-generated by Fern from our API Definition.

export interface WebsiteInfoDto {
    /** Domain the WordPress site is reached at. */
    domain: string;
    /** Full URL of the WordPress site. */
    siteUrl: string;
    /** Site title configured in WordPress. */
    siteName: string;
    /** Tagline or short description configured in WordPress. */
    description: string;
    /** Slug of the currently active WordPress theme. */
    theme: string;
    /** Current operational state of the site. */
    status: string;
    /** Whether the site is served on a temporary platform-provided domain. */
    isTemporaryDomain: boolean;
    /** Whether this site is the primary domain for the instance. */
    isMainDomain: boolean;
    /** Whether this site is a staging site. */
    isStaging: boolean;
    /** Current database size for the site, in bytes. */
    databaseSizeBytes: number;
    /** Current files-on-disk size for the site, in bytes. */
    filesSizeBytes: number;
    /** Number of installed plugins with updates available. */
    pluginUpdatesAvailable?: number | undefined;
    /** Number of installed themes with updates available. */
    themeUpdatesAvailable?: number | undefined;
    /** Version of WordPress currently installed. */
    wordpressVersion?: string | undefined;
}
