// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../index.js";

export interface WebsitesDto {
    /** Whether the operation succeeded. */
    success: boolean;
    /** Sites hosted on the WordPress instance. */
    data?: AmericancloudApi.WebsiteInfoDto[] | undefined;
    /** Error message describing why the operation failed. */
    message?: string | undefined;
}
