// This file was auto-generated by Fern from our API Definition.

export interface WordPressInstanceDto {
    /** Unique identifier for the WordPress instance. */
    id: string;
    /** WordPress username on the hosting platform. */
    username: string;
    /** Display name for the WordPress instance. */
    name: string;
    /** Label of the package currently applied to the instance. */
    packageLabel: string;
    /** Display name of the package currently applied to the instance. */
    packageDisplayName: string;
    /** Monthly billing rate for the current package, in US dollars. */
    rateMonthly: string;
    /** When the WordPress instance was provisioned. */
    createdAt: string;
    /** When the WordPress instance was deleted. Omitted if still active. */
    deletedAt?: (string | null) | undefined;
    /** Whether the WordPress instance is fully provisioned and ready to use. */
    ready: boolean;
}
