// This file was auto-generated by Fern from our API Definition.

export interface ZoneResponseDto {
    /** Zone identifier */
    id: string;
    /** Domain name */
    name: string;
    /** Zone creation date */
    createdAt: string;
}
