// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as AmericancloudApi from "../../../index.js";

export declare namespace PublicIpsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Public IP address allocation, release, and static NAT
 */
export class PublicIpsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PublicIpsClient.Options>;

    constructor(options: PublicIpsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {AmericancloudApi.ListPublicIpsRequest} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.listPublicIps()
     */
    public listPublicIps(
        request: AmericancloudApi.ListPublicIpsRequest = {},
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ListPublicIpsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listPublicIps(request, requestOptions));
    }

    private async __listPublicIps(
        request: AmericancloudApi.ListPublicIpsRequest = {},
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ListPublicIpsResponse>> {
        const { page, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/networks/public-ip",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ListPublicIpsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/networks/public-ip");
    }

    /**
     * Reserves a public IP address and associates it with the specified virtual machine. The region is automatically inferred from the virtual machine. To preview pricing without reserving anything, use POST /networks/public-ip/cost-estimate.
     *
     * @param {AmericancloudApi.ReservePublicIpDto} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.reservePublicIps({
     *         region: "us-west-0"
     *     })
     */
    public reservePublicIps(
        request: AmericancloudApi.ReservePublicIpDto,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.PublicIpResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__reservePublicIps(request, requestOptions));
    }

    private async __reservePublicIps(
        request: AmericancloudApi.ReservePublicIpDto,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.PublicIpResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/networks/public-ip",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.PublicIpResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/networks/public-ip");
    }

    /**
     * @param {AmericancloudApi.ListByIsolatedNetworkPublicIpsRequest} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.listByIsolatedNetworkPublicIps({
     *         isolatedNetworkId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public listByIsolatedNetworkPublicIps(
        request: AmericancloudApi.ListByIsolatedNetworkPublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ListByIsolatedNetworkPublicIpsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listByIsolatedNetworkPublicIps(request, requestOptions));
    }

    private async __listByIsolatedNetworkPublicIps(
        request: AmericancloudApi.ListByIsolatedNetworkPublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ListByIsolatedNetworkPublicIpsResponse>> {
        const { isolatedNetworkId, page, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/networks/public-ip/isolated/${core.url.encodePathParam(isolatedNetworkId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ListByIsolatedNetworkPublicIpsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/networks/public-ip/isolated/{isolatedNetworkId}",
        );
    }

    /**
     * @param {AmericancloudApi.ListByVpcPublicIpsRequest} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.listByVpcPublicIps({
     *         vpcId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public listByVpcPublicIps(
        request: AmericancloudApi.ListByVpcPublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ListByVpcPublicIpsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listByVpcPublicIps(request, requestOptions));
    }

    private async __listByVpcPublicIps(
        request: AmericancloudApi.ListByVpcPublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ListByVpcPublicIpsResponse>> {
        const { vpcId, page, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/networks/public-ip/vpc/${core.url.encodePathParam(vpcId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ListByVpcPublicIpsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/networks/public-ip/vpc/{vpcId}",
        );
    }

    /**
     * @param {AmericancloudApi.GetPublicIpsRequest} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.getPublicIps({
     *         id: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getPublicIps(
        request: AmericancloudApi.GetPublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.PublicIpResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getPublicIps(request, requestOptions));
    }

    private async __getPublicIps(
        request: AmericancloudApi.GetPublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.PublicIpResponseDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/networks/public-ip/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.PublicIpResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/networks/public-ip/{id}",
        );
    }

    /**
     * @param {AmericancloudApi.ReleasePublicIpsRequest} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.releasePublicIps({
     *         id: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public releasePublicIps(
        request: AmericancloudApi.ReleasePublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__releasePublicIps(request, requestOptions));
    }

    private async __releasePublicIps(
        request: AmericancloudApi.ReleasePublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/networks/public-ip/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/networks/public-ip/{id}",
        );
    }

    /**
     * Returns the estimated cost of reserving a public IP address without reserving one.
     *
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.getCostEstimatePublicIps()
     */
    public getCostEstimatePublicIps(
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.CostEstimateResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCostEstimatePublicIps(requestOptions));
    }

    private async __getCostEstimatePublicIps(
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.CostEstimateResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/networks/public-ip/cost-estimate",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.CostEstimateResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/networks/public-ip/cost-estimate",
        );
    }

    /**
     * Changes the source NAT IP for the specified public IP address
     *
     * @param {AmericancloudApi.ChangeSourceNatIpDto} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.changeSourceNatIpPublicIps({
     *         id: "123e4567-e89b-12d3-a456-426614174000",
     *         networkId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public changeSourceNatIpPublicIps(
        request: AmericancloudApi.ChangeSourceNatIpDto,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__changeSourceNatIpPublicIps(request, requestOptions));
    }

    private async __changeSourceNatIpPublicIps(
        request: AmericancloudApi.ChangeSourceNatIpDto,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/networks/public-ip/${core.url.encodePathParam(id)}/change-source-nat-ip`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/v1/networks/public-ip/{id}/change-source-nat-ip",
        );
    }

    /**
     * Enables static NAT for the specified public IP by associating it with a virtual machine
     *
     * @param {AmericancloudApi.EnableStaticNatDto} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.enableStaticNatPublicIps({
     *         id: "123e4567-e89b-12d3-a456-426614174000",
     *         virtualMachineId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public enableStaticNatPublicIps(
        request: AmericancloudApi.EnableStaticNatDto,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__enableStaticNatPublicIps(request, requestOptions));
    }

    private async __enableStaticNatPublicIps(
        request: AmericancloudApi.EnableStaticNatDto,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/networks/public-ip/${core.url.encodePathParam(id)}/enable-static-nat`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/v1/networks/public-ip/{id}/enable-static-nat",
        );
    }

    /**
     * Disables static NAT for the specified public IP address
     *
     * @param {AmericancloudApi.DisableStaticNatPublicIpsRequest} request
     * @param {PublicIpsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.publicIps.disableStaticNatPublicIps({
     *         id: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public disableStaticNatPublicIps(
        request: AmericancloudApi.DisableStaticNatPublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__disableStaticNatPublicIps(request, requestOptions));
    }

    private async __disableStaticNatPublicIps(
        request: AmericancloudApi.DisableStaticNatPublicIpsRequest,
        requestOptions?: PublicIpsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/networks/public-ip/${core.url.encodePathParam(id)}/disable-static-nat`,
            ),
            method: "PUT",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/v1/networks/public-ip/{id}/disable-static-nat",
        );
    }
}
