// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "storageunit01"
 *     }
 */
export interface CreateStorageUnitRequestDto {
    /** Storage unit name. Alphanumeric characters only. */
    name: string;
}
