// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         storageUnitId: "tenant$user",
 *         bucketName: "my-bucket",
 *         purgeObjects: true
 *     }
 */
export interface DeleteBucketObjectStorageRequest {
    /** Storage unit ID (UID) */
    storageUnitId: string;
    /** Bucket name */
    bucketName: string;
    /** Whether to purge objects in the bucket (default: true) */
    purgeObjects?: boolean;
}
