// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         usage: false
 *     }
 */
export interface ListUnitsObjectStorageRequest {
    /** Include latest usage report for each storage unit */
    usage?: boolean;
    /** Page number, 1-indexed. Defaults to 1 when omitted. */
    page?: number;
    /** Items per page. Defaults to 100 when omitted; server cap 500. */
    pageSize?: number;
}
