// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         storageUnitId: "tenant$user"
 *     }
 */
export interface SetUserQuotaRequestDto {
    /** Storage unit ID (UID) */
    storageUnitId: string;
    /** Maximum total size for the storage unit, in gigabytes. */
    maxSizeGb?: number;
    /** When true, removes any existing storage limit instead of setting a value. */
    removeLimit?: boolean;
}
