// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         label: "sjc0"
 *     }
 */
export interface GetByLabelRegionsRequest {
    /** Label of the region to get */
    label: string;
}
