// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "web-tier",
 *         vpcId: "123e4567-e89b-12d3-a456-426614174000",
 *         gateway: "10.0.0.1",
 *         netmask: "255.255.255.0"
 *     }
 */
export interface CreateVpcTierDto {
    /** Human-readable name for the network tier. */
    name: string;
    /** Free-form description of the tier. */
    description?: string;
    /** Identifier of the parent VPC the tier belongs to. */
    vpcId: string;
    /** Network gateway IP for the tier. */
    gateway: string;
    /** Network netmask for the tier. */
    netmask: string;
    /** Identifier of the ACL to apply to the tier. */
    aclId?: string;
}
