// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000",
 *         tierId: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface DeleteTierVpcNetworksRequest {
    /** ID of the VPC that contains the tier */
    id: string;
    /** ID of the network tier to delete */
    tierId: string;
}
