// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface ScaleKubernetesClusterRequest {
    /** ID of the Kubernetes cluster */
    id: string;
    /** Number of worker nodes */
    workerNodes?: number;
    /** Enable or disable autoscaling */
    autoscalingEnabled?: boolean;
    /** Minimum number of worker nodes when autoscaling is enabled */
    minWorkers?: number;
    /** Maximum number of worker nodes when autoscaling is enabled */
    maxWorkers?: number;
}
