// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000",
 *         version: "1.29.0"
 *     }
 */
export interface UpgradeKubernetesClusterRequest {
    /** ID of the Kubernetes cluster */
    id: string;
    /** Kubernetes version to upgrade to (semantic version) */
    version: string;
}
