// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         listId: "123e4567-e89b-12d3-a456-426614174000",
 *         cidrList: "0.0.0.0/0",
 *         protocol: "TCP",
 *         action: "Allow",
 *         trafficType: "Ingress"
 *     }
 */
export interface CreateNetworkAclRuleDto {
    /** ID of the Network ACL List */
    listId: string;
    /** Remote CIDR — source CIDR for `Ingress` rules, destination CIDR for `Egress` rules. */
    cidrList: string;
    /** Protocol the rule applies to. One of `TCP`, `UDP`, `ICMP`, or `ALL`. */
    protocol: string;
    /** Whether to allow or deny matching traffic. */
    action: string;
    /** Direction of traffic the rule applies to. */
    trafficType: string;
    /** Rule number (1-1000). Unique within the ACL list and determines evaluation order. */
    number?: string;
    /** Start of the port range. Used for `TCP` and `UDP` protocols. */
    startPort?: string;
    /** End of the port range. Used for `TCP` and `UDP` protocols. */
    endPort?: string;
    /** ICMP message type. Used for the `ICMP` protocol. */
    icmpType?: string;
    /** ICMP message code. Used for the `ICMP` protocol. */
    icmpCode?: string;
}
