// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *         schedule_name: "schedule_name"
 *     }
 */
export interface DeleteScheduleDatabaseBackupsRequest {
    /** Database cluster ID */
    clusterId: string;
    /** Name of the backup schedule to delete */
    schedule_name: string;
}
