// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface GetScheduleDatabaseBackupsRequest {
    /** Database cluster ID */
    clusterId: string;
    /** Filter by schedule name */
    schedule_name?: string;
    /** Filter by backup policy name */
    backup_policy_name?: string;
}
