// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *         backupMethod: "xtrabackup",
 *         backupPolicyName: "default-backup-policy",
 *         backupName: "manual-2026-05-29",
 *         retentionPeriod: "30d",
 *         deletionPolicy: "Delete"
 *     }
 */
export interface TriggerBackupRequestDto {
    /** Database cluster ID */
    clusterId: string;
    /** Backup method to use for this run. */
    backupMethod: TriggerBackupRequestDto.BackupMethod;
    /** Backup policy that governs this run. */
    backupPolicyName: string;
    /** Name to assign to the resulting backup artifact. */
    backupName: string;
    /** How long to keep the backup. Number followed by `d` (days), `h` (hours), or `m` (minutes). */
    retentionPeriod: string;
    /** Action to take on the backup artifact when the policy is removed. */
    deletionPolicy: TriggerBackupRequestDto.DeletionPolicy;
}

export namespace TriggerBackupRequestDto {
    /** Backup method to use for this run. */
    export const BackupMethod = {
        Xtrabackup: "xtrabackup",
        PgBasebackup: "pg-basebackup",
        Datafile: "datafile",
    } as const;
    export type BackupMethod = (typeof BackupMethod)[keyof typeof BackupMethod];
    /** Action to take on the backup artifact when the policy is removed. */
    export const DeletionPolicy = {
        Delete: "Delete",
        Retain: "Retain",
    } as const;
    export type DeletionPolicy = (typeof DeletionPolicy)[keyof typeof DeletionPolicy];
}
