// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as AmericancloudApi from "../../../index.js";

export declare namespace DatabaseBackupsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * List and restore backups for managed database clusters
 */
export class DatabaseBackupsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DatabaseBackupsClient.Options>;

    constructor(options: DatabaseBackupsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {AmericancloudApi.SetActiveBackupRepoRequestDto} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.setActiveRepoDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         repoName: "primary-backup-repo"
     *     })
     */
    public setActiveRepoDatabaseBackups(
        request: AmericancloudApi.SetActiveBackupRepoRequestDto,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupRepoUpdateResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__setActiveRepoDatabaseBackups(request, requestOptions));
    }

    private async __setActiveRepoDatabaseBackups(
        request: AmericancloudApi.SetActiveBackupRepoRequestDto,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupRepoUpdateResponseDto>> {
        const { clusterId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/repositories/active`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupRepoUpdateResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/v1/databases/clusters/{clusterId}/backups/repositories/active",
        );
    }

    /**
     * @param {AmericancloudApi.ListDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.listDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public listDatabaseBackups(
        request: AmericancloudApi.ListDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupListResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__listDatabaseBackups(request, requestOptions));
    }

    private async __listDatabaseBackups(
        request: AmericancloudApi.ListDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupListResponseDto>> {
        const { clusterId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupListResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}/backups",
        );
    }

    /**
     * @param {AmericancloudApi.TriggerBackupRequestDto} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.triggerDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         backupMethod: "xtrabackup",
     *         backupPolicyName: "default-backup-policy",
     *         backupName: "manual-2026-05-29",
     *         retentionPeriod: "30d",
     *         deletionPolicy: "Delete"
     *     })
     */
    public triggerDatabaseBackups(
        request: AmericancloudApi.TriggerBackupRequestDto,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupTriggerResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__triggerDatabaseBackups(request, requestOptions));
    }

    private async __triggerDatabaseBackups(
        request: AmericancloudApi.TriggerBackupRequestDto,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupTriggerResponseDto>> {
        const { clusterId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupTriggerResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/databases/clusters/{clusterId}/backups",
        );
    }

    /**
     * @param {AmericancloudApi.GetConfigDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.getConfigDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getConfigDatabaseBackups(
        request: AmericancloudApi.GetConfigDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupClusterConfigResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getConfigDatabaseBackups(request, requestOptions));
    }

    private async __getConfigDatabaseBackups(
        request: AmericancloudApi.GetConfigDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupClusterConfigResponseDto>> {
        const { clusterId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/config`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupClusterConfigResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}/backups/config",
        );
    }

    /**
     * @param {AmericancloudApi.GetScheduleDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.getScheduleDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getScheduleDatabaseBackups(
        request: AmericancloudApi.GetScheduleDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupScheduleListResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getScheduleDatabaseBackups(request, requestOptions));
    }

    private async __getScheduleDatabaseBackups(
        request: AmericancloudApi.GetScheduleDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupScheduleListResponseDto>> {
        const { clusterId, schedule_name: scheduleName, backup_policy_name: backupPolicyName } = request;
        const _queryParams: Record<string, unknown> = {
            schedule_name: scheduleName,
            backup_policy_name: backupPolicyName,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/schedule`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupScheduleListResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}/backups/schedule",
        );
    }

    /**
     * @param {AmericancloudApi.CreateScheduleDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.createScheduleDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         body: {
     *             scheduleName: "production-backups",
     *             backupPolicyName: "default-backup-policy",
     *             schedules: [{
     *                     name: "nightly-full",
     *                     backupMethod: "xtrabackup",
     *                     cronExpression: "0 3 * * *"
     *                 }],
     *             pitrEnabled: false
     *         }
     *     })
     */
    public createScheduleDatabaseBackups(
        request: AmericancloudApi.CreateScheduleDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupRepoSetupResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__createScheduleDatabaseBackups(request, requestOptions));
    }

    private async __createScheduleDatabaseBackups(
        request: AmericancloudApi.CreateScheduleDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupRepoSetupResponseDto>> {
        const { clusterId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/schedule`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupRepoSetupResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/databases/clusters/{clusterId}/backups/schedule",
        );
    }

    /**
     * @param {AmericancloudApi.UpdateScheduleDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.updateScheduleDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         body: {
     *             scheduleName: "production-backups",
     *             backupPolicyName: "default-backup-policy",
     *             schedules: [{
     *                     name: "nightly-full",
     *                     backupMethod: "xtrabackup",
     *                     cronExpression: "0 3 * * *"
     *                 }],
     *             pitrEnabled: false
     *         }
     *     })
     */
    public updateScheduleDatabaseBackups(
        request: AmericancloudApi.UpdateScheduleDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupRepoUpdateResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__updateScheduleDatabaseBackups(request, requestOptions));
    }

    private async __updateScheduleDatabaseBackups(
        request: AmericancloudApi.UpdateScheduleDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupRepoUpdateResponseDto>> {
        const { clusterId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/schedule`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupRepoUpdateResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/v1/databases/clusters/{clusterId}/backups/schedule",
        );
    }

    /**
     * @param {AmericancloudApi.DeleteScheduleDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.deleteScheduleDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         schedule_name: "schedule_name"
     *     })
     */
    public deleteScheduleDatabaseBackups(
        request: AmericancloudApi.DeleteScheduleDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupRepoDeleteResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__deleteScheduleDatabaseBackups(request, requestOptions));
    }

    private async __deleteScheduleDatabaseBackups(
        request: AmericancloudApi.DeleteScheduleDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupRepoDeleteResponseDto>> {
        const { clusterId, schedule_name: scheduleName } = request;
        const _queryParams: Record<string, unknown> = {
            schedule_name: scheduleName,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/schedule`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupRepoDeleteResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/databases/clusters/{clusterId}/backups/schedule",
        );
    }

    /**
     * @param {AmericancloudApi.GetPolicyDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.getPolicyDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getPolicyDatabaseBackups(
        request: AmericancloudApi.GetPolicyDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupPolicyListResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getPolicyDatabaseBackups(request, requestOptions));
    }

    private async __getPolicyDatabaseBackups(
        request: AmericancloudApi.GetPolicyDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupPolicyListResponseDto>> {
        const { clusterId, policy_name: policyName } = request;
        const _queryParams: Record<string, unknown> = {
            policy_name: policyName,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/policy`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupPolicyListResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}/backups/policy",
        );
    }

    /**
     * @param {AmericancloudApi.GetDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.getDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         backupName: "nightly-2026-05-28"
     *     })
     */
    public getDatabaseBackups(
        request: AmericancloudApi.GetDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupDetailsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getDatabaseBackups(request, requestOptions));
    }

    private async __getDatabaseBackups(
        request: AmericancloudApi.GetDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupDetailsResponseDto>> {
        const { clusterId, backupName } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/${core.url.encodePathParam(backupName)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupDetailsResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}/backups/{backupName}",
        );
    }

    /**
     * @param {AmericancloudApi.DeleteDatabaseBackupsRequest} request
     * @param {DatabaseBackupsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databaseBackups.deleteDatabaseBackups({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         backupName: "nightly-2026-05-28"
     *     })
     */
    public deleteDatabaseBackups(
        request: AmericancloudApi.DeleteDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BackupDeleteResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDatabaseBackups(request, requestOptions));
    }

    private async __deleteDatabaseBackups(
        request: AmericancloudApi.DeleteDatabaseBackupsRequest,
        requestOptions?: DatabaseBackupsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BackupDeleteResponseDto>> {
        const { clusterId, backupName } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/backups/${core.url.encodePathParam(backupName)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.BackupDeleteResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/databases/clusters/{clusterId}/backups/{backupName}",
        );
    }
}
