// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as AmericancloudApi from "../../../index.js";

export declare namespace WordpressClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Managed WordPress sites
 */
export class WordpressClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WordpressClient.Options>;

    constructor(options: WordpressClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns the active WordPress instance for the account. Returns 404 if the account has no WordPress instance.
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.getWordpress()
     */
    public getWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.WordPressInstanceDto> {
        return core.HttpResponsePromise.fromPromise(this.__getWordpress(requestOptions));
    }

    private async __getWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.WordPressInstanceDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.WordPressInstanceDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/wordpress");
    }

    /**
     * Creates a new WordPress hosting instance for the authenticated account. To preview pricing without creating anything, use POST /wordpress/cost-estimate.
     *
     * @param {AmericancloudApi.CreateWordPressDto} request
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.createWordpress({
     *         packageLabel: "wordpress-10"
     *     })
     */
    public createWordpress(
        request: AmericancloudApi.CreateWordPressDto,
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.WordPressSuccessResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__createWordpress(request, requestOptions));
    }

    private async __createWordpress(
        request: AmericancloudApi.CreateWordPressDto,
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.WordPressSuccessResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.WordPressSuccessResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/wordpress");
    }

    /**
     * Cancels and removes the WordPress instance for the authenticated account
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.cancelWordpress()
     */
    public cancelWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.WordPressSuccessResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__cancelWordpress(requestOptions));
    }

    private async __cancelWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.WordPressSuccessResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress",
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.WordPressSuccessResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api/v1/wordpress");
    }

    /**
     * Returns the estimated cost for a WordPress instance on the given package without creating it. Accepts the same body as create.
     *
     * @param {AmericancloudApi.CreateWordPressDto} request
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.getCostEstimateWordpress({
     *         packageLabel: "wordpress-10"
     *     })
     */
    public getCostEstimateWordpress(
        request: AmericancloudApi.CreateWordPressDto,
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.CostEstimateResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCostEstimateWordpress(request, requestOptions));
    }

    private async __getCostEstimateWordpress(
        request: AmericancloudApi.CreateWordPressDto,
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.CostEstimateResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/cost-estimate",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.CostEstimateResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/wordpress/cost-estimate",
        );
    }

    /**
     * Updates the password for the WordPress hosting account
     *
     * @param {AmericancloudApi.UpdatePasswordDto} request
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.updatePasswordWordpress({
     *         newPassword: "newPassword"
     *     })
     */
    public updatePasswordWordpress(
        request: AmericancloudApi.UpdatePasswordDto,
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.WordPressSuccessResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__updatePasswordWordpress(request, requestOptions));
    }

    private async __updatePasswordWordpress(
        request: AmericancloudApi.UpdatePasswordDto,
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.WordPressSuccessResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/password",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.WordPressSuccessResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/api/v1/wordpress/password");
    }

    /**
     * Creates a login session URL for managing your WordPress hosting
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.createSessionWordpress()
     */
    public createSessionWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.SessionResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__createSessionWordpress(requestOptions));
    }

    private async __createSessionWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.SessionResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/session",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.SessionResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/wordpress/session");
    }

    /**
     * Returns disk and resource quota information for the WordPress instance
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.getQuotaWordpress()
     */
    public getQuotaWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.QuotaInfoDto> {
        return core.HttpResponsePromise.fromPromise(this.__getQuotaWordpress(requestOptions));
    }

    private async __getQuotaWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.QuotaInfoDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/quota",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.QuotaInfoDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/wordpress/quota");
    }

    /**
     * Returns the maximum number of WordPress sites allowed for the current package
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.getMaxInstancesWordpress()
     */
    public getMaxInstancesWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.MaxInstancesDto> {
        return core.HttpResponsePromise.fromPromise(this.__getMaxInstancesWordpress(requestOptions));
    }

    private async __getMaxInstancesWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.MaxInstancesDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/max-instances",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.MaxInstancesDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/wordpress/max-instances",
        );
    }

    /**
     * Returns a list of all WordPress websites/sites for the account
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.listWebsitesWordpress()
     */
    public listWebsitesWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.WebsitesDto> {
        return core.HttpResponsePromise.fromPromise(this.__listWebsitesWordpress(requestOptions));
    }

    private async __listWebsitesWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.WebsitesDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/websites",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.WebsitesDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/wordpress/websites");
    }

    /**
     * Returns bandwidth usage statistics for the WordPress instance
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.getBandwidthWordpress()
     */
    public getBandwidthWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.BandwidthDto> {
        return core.HttpResponsePromise.fromPromise(this.__getBandwidthWordpress(requestOptions));
    }

    private async __getBandwidthWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.BandwidthDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/bandwidth",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.BandwidthDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/wordpress/bandwidth");
    }

    /**
     * Returns the nameserver addresses for the WordPress hosting server
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.getNameserversWordpress()
     */
    public getNameserversWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.NameserversDto> {
        return core.HttpResponsePromise.fromPromise(this.__getNameserversWordpress(requestOptions));
    }

    private async __getNameserversWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.NameserversDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/nameservers",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.NameserversDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/wordpress/nameservers");
    }

    /**
     * Upgrades the WordPress instance to a higher tier package/plan
     *
     * @param {AmericancloudApi.ChangePackageDto} request
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.changePackageWordpress({
     *         packageLabel: "wordpress-25"
     *     })
     */
    public changePackageWordpress(
        request: AmericancloudApi.ChangePackageDto,
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.WordPressSuccessResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__changePackageWordpress(request, requestOptions));
    }

    private async __changePackageWordpress(
        request: AmericancloudApi.ChangePackageDto,
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.WordPressSuccessResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/package",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.WordPressSuccessResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/api/v1/wordpress/package");
    }

    /**
     * Returns all available WordPress hosting packages/plans
     *
     * @param {AmericancloudApi.ListPackagesWordpressRequest} request
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.listPackagesWordpress()
     */
    public listPackagesWordpress(
        request: AmericancloudApi.ListPackagesWordpressRequest = {},
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ListPackagesWordpressResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listPackagesWordpress(request, requestOptions));
    }

    private async __listPackagesWordpress(
        request: AmericancloudApi.ListPackagesWordpressRequest = {},
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ListPackagesWordpressResponse>> {
        const { page, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/packages",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ListPackagesWordpressResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/wordpress/packages");
    }

    /**
     * Returns the current package for the account's WordPress instance
     *
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.getCurrentPackageWordpress()
     */
    public getCurrentPackageWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.WordPressPackageDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCurrentPackageWordpress(requestOptions));
    }

    private async __getCurrentPackageWordpress(
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.WordPressPackageDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/packages/current",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.WordPressPackageDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/wordpress/packages/current",
        );
    }

    /**
     * Returns packages available for upgrade (higher tier than current)
     *
     * @param {AmericancloudApi.ListUpgradePackagesWordpressRequest} request
     * @param {WordpressClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.wordpress.listUpgradePackagesWordpress()
     */
    public listUpgradePackagesWordpress(
        request: AmericancloudApi.ListUpgradePackagesWordpressRequest = {},
        requestOptions?: WordpressClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ListUpgradePackagesWordpressResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listUpgradePackagesWordpress(request, requestOptions));
    }

    private async __listUpgradePackagesWordpress(
        request: AmericancloudApi.ListUpgradePackagesWordpressRequest = {},
        requestOptions?: WordpressClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ListUpgradePackagesWordpressResponse>> {
        const { page, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/wordpress/packages/upgrades",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ListUpgradePackagesWordpressResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/wordpress/packages/upgrades",
        );
    }
}
