// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         newPassword: "newPassword"
 *     }
 */
export interface UpdatePasswordDto {
    /** New password for the WordPress hosting account */
    newPassword: string;
}
