// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as AmericancloudApi from "../../../index.js";

export declare namespace SnapshotsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Point-in-time snapshots of block storage and root volumes
 */
export class SnapshotsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SnapshotsClient.Options>;

    constructor(options: SnapshotsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns all snapshots for the authenticated account
     *
     * @param {AmericancloudApi.ListSnapshotsRequest} request
     * @param {SnapshotsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.snapshots.listSnapshots()
     */
    public listSnapshots(
        request: AmericancloudApi.ListSnapshotsRequest = {},
        requestOptions?: SnapshotsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ListSnapshotsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSnapshots(request, requestOptions));
    }

    private async __listSnapshots(
        request: AmericancloudApi.ListSnapshotsRequest = {},
        requestOptions?: SnapshotsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ListSnapshotsResponse>> {
        const { page, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/storage/snapshots",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ListSnapshotsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/storage/snapshots");
    }

    /**
     * Creates a new snapshot from a block storage volume. To preview pricing without creating anything, use POST /storage/snapshots/cost-estimate.
     *
     * @param {AmericancloudApi.CreateSnapshotDto} request
     * @param {SnapshotsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.snapshots.createSnapshots({
     *         volumeId: "vol-123456",
     *         name: "my-data-snapshot",
     *         type: "DataDisk"
     *     })
     */
    public createSnapshots(
        request: AmericancloudApi.CreateSnapshotDto,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.SnapshotResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__createSnapshots(request, requestOptions));
    }

    private async __createSnapshots(
        request: AmericancloudApi.CreateSnapshotDto,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.SnapshotResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/storage/snapshots",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.SnapshotResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/storage/snapshots");
    }

    /**
     * Returns details of a specific snapshot
     *
     * @param {AmericancloudApi.GetSnapshotsRequest} request
     * @param {SnapshotsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.snapshots.getSnapshots({
     *         id: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getSnapshots(
        request: AmericancloudApi.GetSnapshotsRequest,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.SnapshotResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getSnapshots(request, requestOptions));
    }

    private async __getSnapshots(
        request: AmericancloudApi.GetSnapshotsRequest,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.SnapshotResponseDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/storage/snapshots/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AmericancloudApi.SnapshotResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/storage/snapshots/{id}",
        );
    }

    /**
     * Deletes a snapshot. This operation cannot be undone.
     *
     * @param {AmericancloudApi.DeleteSnapshotsRequest} request
     * @param {SnapshotsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.snapshots.deleteSnapshots({
     *         id: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public deleteSnapshots(
        request: AmericancloudApi.DeleteSnapshotsRequest,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.SnapshotOperationResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSnapshots(request, requestOptions));
    }

    private async __deleteSnapshots(
        request: AmericancloudApi.DeleteSnapshotsRequest,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.SnapshotOperationResponseDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/storage/snapshots/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.SnapshotOperationResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/storage/snapshots/{id}",
        );
    }

    /**
     * Returns the estimated cost for a snapshot of the given volume without creating it. Accepts the same body as create.
     *
     * @param {AmericancloudApi.CreateSnapshotDto} request
     * @param {SnapshotsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.snapshots.getCostEstimateSnapshots({
     *         volumeId: "vol-123456",
     *         name: "my-data-snapshot",
     *         type: "DataDisk"
     *     })
     */
    public getCostEstimateSnapshots(
        request: AmericancloudApi.CreateSnapshotDto,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.CostEstimateResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCostEstimateSnapshots(request, requestOptions));
    }

    private async __getCostEstimateSnapshots(
        request: AmericancloudApi.CreateSnapshotDto,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.CostEstimateResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/storage/snapshots/cost-estimate",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.CostEstimateResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/storage/snapshots/cost-estimate",
        );
    }

    /**
     * Reverts the volume associated with this snapshot to its point-in-time state.
     *
     * @param {AmericancloudApi.RevertSnapshotsRequest} request
     * @param {SnapshotsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.snapshots.revertSnapshots({
     *         id: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public revertSnapshots(
        request: AmericancloudApi.RevertSnapshotsRequest,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.SnapshotOperationResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__revertSnapshots(request, requestOptions));
    }

    private async __revertSnapshots(
        request: AmericancloudApi.RevertSnapshotsRequest,
        requestOptions?: SnapshotsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.SnapshotOperationResponseDto>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/storage/snapshots/${core.url.encodePathParam(id)}/revert`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.SnapshotOperationResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/storage/snapshots/{id}/revert",
        );
    }
}
