// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../../../index.js";

export interface ListSnapshotsBlockStorageResponse extends AmericancloudApi.PaginatedResponseDto {
    data: AmericancloudApi.SnapshotResponseDto[];
}
