// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../../../index.js";

export interface ListListsByVpcNetworkAclsResponse extends AmericancloudApi.PaginatedResponseDto {
    data: AmericancloudApi.NetworkAclListResponseDto[];
}
