// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         label: "ubuntu-22.04"
 *     }
 */
export interface GetByLabelImagesRequest {
    /** Label of the image to get */
    label: string;
}
