// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../../../index.js";

export interface ListLoadBalancerRulesResponse extends AmericancloudApi.PaginatedResponseDto {
    data: AmericancloudApi.LoadBalancerRuleResponseDto[];
}
