// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../../../../index.js";

/**
 * @example
 *     {
 *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *         type: "public"
 *     }
 */
export interface DeleteLoadBalancerDatabasesRequest {
    /** Database cluster ID */
    clusterId: string;
    /** Load balancer type */
    type: AmericancloudApi.DeleteLoadBalancerDatabasesRequestType;
}
