// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *         offeringId: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface ResizeDatabaseClusterDto {
    /** Database cluster ID */
    clusterId: string;
    /** Identifier of the target database offering to resize to. */
    offeringId: string;
    /** New storage capacity for the cluster, in gigabytes. */
    storageGb?: number;
}
