// This file was auto-generated by Fern from our API Definition.

export const ListDatabaseOfferingsRequestType = {
    Postgres: "postgres",
    Mysql: "mysql",
    Redis: "redis",
    Elasticsearch: "elasticsearch",
} as const;
export type ListDatabaseOfferingsRequestType =
    (typeof ListDatabaseOfferingsRequestType)[keyof typeof ListDatabaseOfferingsRequestType];
