// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ipId: "123e4567-e89b-12d3-a456-426614174000",
 *         privatePort: "80",
 *         publicPort: "8080",
 *         protocol: "TCP",
 *         vmId: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface CreatePortForwardingRuleDto {
    /** ID of the public IP address */
    ipId: string;
    /** Port on the VM that traffic is forwarded to. Must be 1-65535. */
    privatePort: string;
    /** Port on the public IP that receives the inbound traffic. Must be 1-65535. */
    publicPort: string;
    /** Protocol the forwarding rule applies to. */
    protocol: CreatePortForwardingRuleDto.Protocol;
    /** Identifier of the VM the forwarded traffic is delivered to. */
    vmId: string;
    /** When `true`, automatically creates a matching firewall rule alongside the port forwarding rule. */
    openFirewall?: string;
}

export namespace CreatePortForwardingRuleDto {
    /** Protocol the forwarding rule applies to. */
    export const Protocol = {
        Tcp: "TCP",
        Udp: "UDP",
    } as const;
    export type Protocol = (typeof Protocol)[keyof typeof Protocol];
}
