// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ipId: "123e4567-e89b-12d3-a456-426614174000",
 *         privatePort: "80",
 *         publicPort: "8080",
 *         protocol: "TCP",
 *         vmId: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface CreatePortForwardingRuleDto {
    /** ID of the public IP address */
    ipId: string;
    /** Port on the VM that traffic is forwarded to. Must be 1-65535. */
    privatePort: string;
    /** Port on the public IP that receives the inbound traffic. Must be 1-65535. */
    publicPort: string;
    /** Protocol the forwarding rule applies to. */
    protocol: CreatePortForwardingRuleDto.Protocol;
    /** Identifier of the VM the forwarded traffic is delivered to. */
    vmId: string;
    /** When `true`, automatically creates a matching firewall rule alongside the port forwarding rule. */
    openFirewall?: string;
    /** For a public IP reserved in a VPC, the VPC tier the rule applies to. A VPC IP is not bound to any single tier, so the rule must target one. You only need to set this when the VM has interfaces in more than one tier of the VPC — otherwise the tier is determined automatically from the VM. Ignored for IPs reserved in an isolated network. */
    tierId?: string;
}

export namespace CreatePortForwardingRuleDto {
    /** Protocol the forwarding rule applies to. */
    export const Protocol = {
        Tcp: "TCP",
        Udp: "UDP",
    } as const;
    export type Protocol = (typeof Protocol)[keyof typeof Protocol];
}
