// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "production-network",
 *         region: "sjc0"
 *     }
 */
export interface CreateIsolatedNetworkDto {
    /** Human-readable name for the network. */
    name: string;
    /** Free-form description of the network. */
    description?: string;
    /** Region the network will be created in. References a region label from /v1/compute/regions. */
    region: string;
    /** Network netmask. */
    netmask?: string;
    /** Network gateway IP. */
    gateway?: string;
}
