// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000",
 *         hours: 24,
 *         sample_period: 10
 *     }
 */
export interface GetMetricsVmsRequest {
    /** ID of the virtual machine */
    id: string;
    /** Number of hours to look back (1-16) */
    hours: number;
    /** Sampling step — return every Nth data point from the raw dataset. Higher values return fewer, more spread-out points. When omitted, up to 150 points are returned. */
    sample_period?: number;
}
