// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000",
 *         sizeGb: 200
 *     }
 */
export interface ResizeVmDiskDto {
    /** ID of the virtual machine */
    id: string;
    /** The new size of the root disk in GB. Must be larger than the current root disk size. */
    sizeGb: number;
    /** Whether to automatically reboot the VM after the resize completes. Only applies when the VM is running. A reboot is required for the OS to recognize the new disk size. */
    reboot?: boolean;
}
