// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface ScaleVmDto {
    /** ID of the virtual machine */
    id: string;
    /** Number of virtual CPUs. Optional, but at least one of CPU or memory must be provided. */
    cpu?: number;
    /** Memory in MB. Optional, but at least one of CPU or memory must be provided. */
    memoryMb?: number;
}
