// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000",
 *         hostname: "my-web-server"
 *     }
 */
export interface UpdateHostnameVmsRequest {
    /** ID of the virtual machine */
    id: string;
    /** The new hostname for the virtual machine */
    hostname: string;
}
