// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userClusterId: "123e4567-e89b-12d3-a456-426614174000",
 *         repoName: "primary-backup-repo",
 *         bucket: "my-storage-bucket",
 *         endpoint: "https://s3.example.com",
 *         accessKeyId: "AKIAIOSFODNN7EXAMPLE",
 *         accessKeySecret: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
 *     }
 */
export interface SetupBackupRepoRequestDto {
    /** Infrastructure cluster ID */
    userClusterId: string;
    /** Name for the backup repository. */
    repoName: string;
    /** S3 bucket backups are stored in. */
    bucket: string;
    /** S3-compatible endpoint URL to use for the bucket. */
    endpoint: string;
    /** S3 access key identifier with access to the bucket. */
    accessKeyId: string;
    /** S3 secret key paired with the access key. */
    accessKeySecret: string;
    /** Optional key prefix to store backups under, inside the bucket. */
    pathPrefix?: string;
}
