// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         correlationId: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface GetStatusDatabaseOperationsRequest {
    /** Operation correlation ID */
    correlationId: string;
}
