// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as AmericancloudApi from "../../../index.js";

export declare namespace DatabasesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Managed database clusters (MySQL, PostgreSQL, Redis)
 */
export class DatabasesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DatabasesClient.Options>;

    constructor(options: DatabasesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns all database clusters for the authenticated account.
     *
     * @param {AmericancloudApi.ListDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.listDatabases()
     */
    public listDatabases(
        request: AmericancloudApi.ListDatabasesRequest = {},
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ListDatabasesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listDatabases(request, requestOptions));
    }

    private async __listDatabases(
        request: AmericancloudApi.ListDatabasesRequest = {},
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ListDatabasesResponse>> {
        const { user_cluster_id: userClusterId, page, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            user_cluster_id: userClusterId,
            page,
            pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/databases/clusters",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ListDatabasesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/databases/clusters");
    }

    /**
     * Creates a new managed database cluster for the authenticated account.
     *
     * @param {AmericancloudApi.CreateDatabaseClusterDto} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.createDatabases({
     *         dbClusterName: "production-db",
     *         regionId: "123e4567-e89b-12d3-a456-426614174000",
     *         tier: "standard",
     *         availabilityType: "single-node"
     *     })
     */
    public createDatabases(
        request: AmericancloudApi.CreateDatabaseClusterDto,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.CreateClusterResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__createDatabases(request, requestOptions));
    }

    private async __createDatabases(
        request: AmericancloudApi.CreateDatabaseClusterDto,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.CreateClusterResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                "api/v1/databases/clusters",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.CreateClusterResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/databases/clusters");
    }

    /**
     * Returns the estimated monthly cost for deploying a database. If user_cluster_id is provided, calculates the marginal cost on an existing cluster.
     *
     * @param {AmericancloudApi.GetCostEstimateDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.getCostEstimateDatabases({
     *         offeringId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getCostEstimateDatabases(
        request: AmericancloudApi.GetCostEstimateDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.DbsCostEstimateResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCostEstimateDatabases(request, requestOptions));
    }

    private async __getCostEstimateDatabases(
        request: AmericancloudApi.GetCostEstimateDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.DbsCostEstimateResponseDto>> {
        const {
            offeringId,
            user_cluster_id: userClusterId,
            availability_type: availabilityType,
            storage_gb: storageGb,
            tier,
            db_cluster_id: dbClusterId,
        } = request;
        const _queryParams: Record<string, unknown> = {
            user_cluster_id: userClusterId,
            availability_type: availabilityType,
            storage_gb: storageGb,
            tier,
            db_cluster_id: dbClusterId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/cost/${core.url.encodePathParam(offeringId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.DbsCostEstimateResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/cost/{offeringId}",
        );
    }

    /**
     * @param {AmericancloudApi.GetDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.getDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getDatabases(
        request: AmericancloudApi.GetDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ClusterDetailResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getDatabases(request, requestOptions));
    }

    private async __getDatabases(
        request: AmericancloudApi.GetDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ClusterDetailResponseDto>> {
        const { clusterId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ClusterDetailResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}",
        );
    }

    /**
     * Permanently deletes a database cluster. This operation cannot be undone.
     *
     * @param {AmericancloudApi.DeleteDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.deleteDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public deleteDatabases(
        request: AmericancloudApi.DeleteDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ClusterActionResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDatabases(request, requestOptions));
    }

    private async __deleteDatabases(
        request: AmericancloudApi.DeleteDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ClusterActionResponseDto>> {
        const { clusterId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ClusterActionResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/databases/clusters/{clusterId}",
        );
    }

    /**
     * @param {AmericancloudApi.GetStatusDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.getStatusDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getStatusDatabases(
        request: AmericancloudApi.GetStatusDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ClusterStatusResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getStatusDatabases(request, requestOptions));
    }

    private async __getStatusDatabases(
        request: AmericancloudApi.GetStatusDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ClusterStatusResponseDto>> {
        const { clusterId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/status`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ClusterStatusResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}/status",
        );
    }

    /**
     * Returns connection details for the database cluster.
     *
     * @param {AmericancloudApi.GetConnectionDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.getConnectionDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         includePassword: "includePassword"
     *     })
     */
    public getConnectionDatabases(
        request: AmericancloudApi.GetConnectionDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ConnectionInfoResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getConnectionDatabases(request, requestOptions));
    }

    private async __getConnectionDatabases(
        request: AmericancloudApi.GetConnectionDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ConnectionInfoResponseDto>> {
        const { clusterId, includePassword } = request;
        const _queryParams: Record<string, unknown> = {
            includePassword,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/connection`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ConnectionInfoResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}/connection",
        );
    }

    /**
     * @param {AmericancloudApi.GetOperationsDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.getOperationsDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public getOperationsDatabases(
        request: AmericancloudApi.GetOperationsDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.RecentOperationsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getOperationsDatabases(request, requestOptions));
    }

    private async __getOperationsDatabases(
        request: AmericancloudApi.GetOperationsDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.RecentOperationsResponseDto>> {
        const { clusterId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/operations`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.RecentOperationsResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/databases/clusters/{clusterId}/operations",
        );
    }

    /**
     * @param {AmericancloudApi.StartDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.startDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public startDatabases(
        request: AmericancloudApi.StartDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ClusterActionResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__startDatabases(request, requestOptions));
    }

    private async __startDatabases(
        request: AmericancloudApi.StartDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ClusterActionResponseDto>> {
        const { clusterId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/start`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ClusterActionResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/databases/clusters/{clusterId}/start",
        );
    }

    /**
     * @param {AmericancloudApi.StopDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.stopDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public stopDatabases(
        request: AmericancloudApi.StopDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ClusterActionResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__stopDatabases(request, requestOptions));
    }

    private async __stopDatabases(
        request: AmericancloudApi.StopDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ClusterActionResponseDto>> {
        const { clusterId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/stop`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ClusterActionResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/databases/clusters/{clusterId}/stop",
        );
    }

    /**
     * Changes the database cluster to a different offering or storage size.
     *
     * @param {AmericancloudApi.ResizeDatabaseClusterDto} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.resizeDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         offeringId: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public resizeDatabases(
        request: AmericancloudApi.ResizeDatabaseClusterDto,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<AmericancloudApi.ClusterActionResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__resizeDatabases(request, requestOptions));
    }

    private async __resizeDatabases(
        request: AmericancloudApi.ResizeDatabaseClusterDto,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<AmericancloudApi.ClusterActionResponseDto>> {
        const { clusterId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/resize`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as AmericancloudApi.ClusterActionResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/databases/clusters/{clusterId}/resize",
        );
    }

    /**
     * @param {AmericancloudApi.ModifyLoadBalancerRequestDto} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.modifyLoadBalancerDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         type: "public"
     *     })
     */
    public modifyLoadBalancerDatabases(
        request: AmericancloudApi.ModifyLoadBalancerRequestDto,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__modifyLoadBalancerDatabases(request, requestOptions));
    }

    private async __modifyLoadBalancerDatabases(
        request: AmericancloudApi.ModifyLoadBalancerRequestDto,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { clusterId, type: type_, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/load-balancers/${core.url.encodePathParam(type_)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/databases/clusters/{clusterId}/load-balancers/{type}",
        );
    }

    /**
     * @param {AmericancloudApi.DeleteLoadBalancerDatabasesRequest} request
     * @param {DatabasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmericancloudApi.BadRequestError}
     * @throws {@link AmericancloudApi.UnauthorizedError}
     * @throws {@link AmericancloudApi.ForbiddenError}
     * @throws {@link AmericancloudApi.NotFoundError}
     * @throws {@link AmericancloudApi.ConflictError}
     * @throws {@link AmericancloudApi.InternalServerError}
     *
     * @example
     *     await client.databases.deleteLoadBalancerDatabases({
     *         clusterId: "123e4567-e89b-12d3-a456-426614174000",
     *         type: "public"
     *     })
     */
    public deleteLoadBalancerDatabases(
        request: AmericancloudApi.DeleteLoadBalancerDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteLoadBalancerDatabases(request, requestOptions));
    }

    private async __deleteLoadBalancerDatabases(
        request: AmericancloudApi.DeleteLoadBalancerDatabasesRequest,
        requestOptions?: DatabasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { clusterId, type: type_ } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-API-Client-Secret": requestOptions?.apiClientSecret ?? this._options?.apiClientSecret,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmericancloudApiEnvironment.Production,
                `api/v1/databases/clusters/${core.url.encodePathParam(clusterId)}/load-balancers/${core.url.encodePathParam(type_)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmericancloudApi.BadRequestError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 401:
                    throw new AmericancloudApi.UnauthorizedError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 403:
                    throw new AmericancloudApi.ForbiddenError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AmericancloudApi.NotFoundError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 409:
                    throw new AmericancloudApi.ConflictError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                case 500:
                    throw new AmericancloudApi.InternalServerError(
                        _response.error.body as AmericancloudApi.ApiErrorDto,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AmericancloudApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/databases/clusters/{clusterId}/load-balancers/{type}",
        );
    }
}
