// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000",
 *         vmId: "f8d7e91c-f24d-4c21-b75e-4c7c5389c305"
 *     }
 */
export interface AttachVolumeDto {
    /** Volume ID */
    id: string;
    /** The ID of the virtual machine to attach the volume to */
    vmId: string;
}
