// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListBlockStorageRequest {
    /** Filter volumes attached to a specific virtual machine */
    vmId?: string;
    /** Page number, 1-indexed. Defaults to 1 when omitted. */
    page?: number;
    /** Items per page. Defaults to 100 when omitted; server cap 500. */
    pageSize?: number;
}
