// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         protocol: "TCP"
 *     }
 */
export interface CreateEgressRuleDto {
    /** Protocol the rule applies to. One of `TCP`, `UDP`, `ICMP`, or `ALL`. */
    protocol: string;
    /** Start of the port range the rule applies to. */
    startPort?: string;
    /** End of the port range the rule applies to. */
    endPort?: string;
    /** Source CIDR within the guest network CIDR. Omit to allow the entire network. */
    sourceCidrList?: string;
    /** Destination CIDR the traffic is allowed to reach. Defaults to `0.0.0.0/0`. */
    destCidrList?: string;
    /** Identifier of the network the egress rule applies to. */
    networkId?: string;
}
