// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         networkId: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface ListByNetworkEgressRulesRequest {
    /** ID of the network */
    networkId: string;
    /** Page number, 1-indexed. Defaults to 1 when omitted. */
    page?: number;
    /** Items per page. Defaults to 100 when omitted; server cap 500. */
    pageSize?: number;
}
