// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface UpdateEgressRuleDto {
    /** ID of the egress rule */
    id: string;
    /** Source CIDR within the guest network CIDR. */
    sourceCidrList?: string;
    /** Destination CIDR the traffic is allowed to reach. */
    destCidrList?: string;
    /** Start of the port range the rule applies to. */
    startPort?: string;
    /** End of the port range the rule applies to. */
    endPort?: string;
}
