// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "my-ssh-key"
 *     }
 */
export interface DeleteSshKeysRequest {
    /** Name of the SSH key pair to delete */
    name: string;
}
