// This file was auto-generated by Fern from our API Definition.

import type * as AmericancloudApi from "../../../index.js";

/**
 * Network the cluster will attach to. Required when creating a new cluster; omit only when deploying onto an existing `userClusterId`.
 */
export type CreateDatabaseClusterDtoNetworkConfig =
    | AmericancloudApi.CreateDatabaseClusterDtoNetworkConfig.Isolated
    | AmericancloudApi.CreateDatabaseClusterDtoNetworkConfig.Vpc;

export namespace CreateDatabaseClusterDtoNetworkConfig {
    export interface Isolated extends AmericancloudApi.IsolatedNetworkConfigDto {
        networkType: "isolated";
    }

    export interface Vpc extends AmericancloudApi.VpcNetworkConfigDto {
        networkType: "vpc";
    }
}
