// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         region: "us-west-0"
 *     }
 */
export interface ReservePublicIpDto {
    /** Identifier of the isolated network the public IP should attach to. */
    networkId?: string;
    /** Identifier of the VPC the public IP should attach to. */
    vpcId?: string;
    /** Label of the region where the IP address should be allocated */
    region: string;
}
